#####Config file for BedHome v2.17 by Superior_Slime#####
###Boolean values. If these are not set to true or false, you and your players WILL get errors. You have been warned.###
##Whether to use permissions or allow all players to do /bed
permissions: true
#Should we automatically download and install new updates?
auto-update: true
#Should player actions (such as teleporting to a bed or setting one) be logged to the console?
console_messages: false

##What to do if a player has no bed.
#"nobedmode: a" Allow. Players will be able to teleport to past beds if they have no bed.
#"nobedmode: b" Block. Players will be given the error message that they have no bed.
#"nobedmode: c" Co-ordinates. Players will be given their past bed's co-ordinates, if they exist.
nobedmode: c
##What language to use. Availible: en (English), es (Spanish), German (de), fr (French), pt (Portuguese) and dn (Danish)
locale: en
###If you specify a language that doesn't exist, the plugin will just use English.
