#####Config file for BedHome v2.1 by Superior_Slime#####
###Boolean values. If these are not set to true or false, you and your players WILL get errors. You have been warned.###
##Whether to use permissions or allow all players to do /bed
permissions: true
#Should we automatically download and install new updates?
auto-update: true


##What to do if a player has no bed.
#"nobedmode: a" Allow. Players will be able to teleport to past beds if they have no bed.
#"nobedmode: b" Block. Players will be given the error message defined below as "nobed"
#"nobedmode: c" Co-ordinates. Players will be given their past bed's co-ordinates, if they exist.
nobedmode: c

