name: BedHome
main: me.Superior_Slime.bedhome.main
version: 2.0
description: >
             Teleport to your bed with a command!
commands:
    bed:
        description: Teleport to your bed.
        permission: bedhome.bed

