name: BedHome
main: org.minecast.bedhome.Main
version: '@Version@'
authors: [Superior_Slime, HeroCC]
softdepend: [Vault]
description: 'Teleport to your bed with a command: /bed!'
commands:
    bed:
        description: Teleport to your bed!
        usage: /bed [world]
        permission: bedhome.bed
    bedhome:
        description: Reload the config or get help.
        usage: /bedhome [reload|lookup|teleport] <player> <world>
        aliases: [bh]
        permission: bedhome.admin
    bhdebug:
        description: Debug command
        Usage: /<command>

    
permissions:
  bedhome.bed:
    description: "Allows players to use /bed"
  bedhome.admin:
    description: "Allows players to use all mod commands"
    children:
      bedhome.lookup: true
      bedhome.config: true
  bedhome.world:
    description: "Allows players to /bed to another world"
  bedhome.lookup:
    description: "Allows players to lookup the location of someone's bed"
  bedhome.config:
    description: "Allows players to reload and modify configuration files"
